version: "3.4"
services:
    jdk:
        build:
            context: ./java
            dockerfile: DockerFile.jdk
            labels:
                com.enioka.description: "build helper - OpenJDK JDK for windows nano"
            args:
                - OJDK_SHA256=7F34BB39C19A82D453A0DC2182BEE6B16182E9475A4B22D4143172B26EA68E0D
                - WINDOWS_TAG=${WINDOWS_TAG}
                - JAVA_VERSION=11
                - OJDK_PATH_VERSION=11.0.2-1
                - OJDK_ZIP_VERSION=11.0.2.7-1
        image: enioka/buildhelpers:jdk-1.11-${WINDOWS_TAG:?tag must be given}
        hostname: jdk

    mvn:
        build:
            context: ./maven
            dockerfile: DockerFile
            labels:
                com.enioka.description: "build helper - Maven build for windows nano"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
                - MVN_VERSION=3.6.0
                - MVN_SHA512=7d14ab2b713880538974aa361b987231473fbbed20e83586d542c691ace1139026f232bd46fdcce5e8887f528ab1c3fbfc1b2adec90518b6941235952d3868e9
                - JAVA_VERSION=1.11
        image: enioka/buildhelpers:maven-3-${WINDOWS_TAG:?tag must be given}
        hostname: maven

    jqm:
        build:
            context: ../../
            dockerfile: ./docker/windows/jqm/Dockerfile
            labels:
                com.enioka.description: "official JQM Docker distribution"
            args:
                - WINDOWS_TAG=${WINDOWS_TAG}
        image: ${JQM_IMAGE_NAME}
