ARG WINDOWS_TAG
ARG JAVA_VERSION=1.8.0

FROM mcr.microsoft.com/powershell:nanoserver-${WINDOWS_TAG} as installer

SHELL ["pwsh.exe", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# http://www-us.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip
ARG MVN_VERSION
ARG MVN_SHA512

ENV MVN_URL http://www-us.apache.org/dist/maven/maven-3/${MVN_VERSION}/binaries/apache-maven-${MVN_VERSION}-bin.zip

RUN Write-Host ('Downloading {0} ...' -f $env:MVN_URL); \
    mkdir /TEMP >$null; \
    Invoke-WebRequest -Uri $env:MVN_URL -OutFile '/TEMP/mvn.zip' -UseBasicParsing ; \
    Write-Host ('Verifying sha512 ({0}) ...' -f $env:MVN_SHA512); \
    if ((Get-FileHash /TEMP/mvn.zip -Algorithm sha512).Hash -ne $env:MVN_SHA512) { \
    Write-Host 'FAILED!'; \
    exit 1; \
    };

RUN	Write-Host 'Expanding ...'; \
    Expand-Archive /TEMP/mvn.zip -DestinationPath C:\; \
    \
    Write-Host 'Renaming ...'; \
    Move-Item apache* C:/mvn; \
    \
    Write-Host 'Removing ...'; \
    Remove-Item /TEMP/mvn.zip -Force; \
    \
    Write-Host 'Complete.';



FROM enioka/buildhelpers:jdk-${JAVA_VERSION}-${WINDOWS_TAG}

COPY --from=installer C:/mvn/ C:/mvn/

USER ContainerAdministrator
RUN setx /M PATH %PATH%;C:\mvn\bin
USER ContainerUser

LABEL maintainer="Enioka" \
    readme.md="https://github.com/enioka/jqm/blob/master/README.md" \
    description="Maven packaging"
